# Generated by Django 6.0.4 on 2026-09-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0022_alter_validacaodataconcluida_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notas_participantes",
            old_name="numero_documento",
            new_name="numero_importacao",
        ),
        migrations.AddField(
            model_name="notas_participantes",
            name="cod_situacao",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Código de Situação"
            ),
        ),
    ]
