# Generated by Django 6.0.6 on 2026-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0035_alter_empresa_indicador_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_itens_sped',
            name='descricao_prod',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição do Produto'),
        ),
        migrations.AlterField(
            model_name='cadastro_itens_sped',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gênero'),
        ),
    ]
