# Generated by Django 6.0.4 on 2026-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historico", "0006_remove_historico_entidade_titular_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historico",
            name="entidade_filho",
        ),
        migrations.RemoveField(
            model_name="historico",
            name="entidade_pai",
        ),
        migrations.AddField(
            model_name="historico",
            name="documento",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Documento"
            ),
        ),
        migrations.AddField(
            model_name="historico",
            name="reg_titular",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Registro Titular"
            ),
        ),
        migrations.AddField(
            model_name="historico",
            name="serie",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Série"
            ),
        ),
    ]
